### ISSUE TITLE
imageView like IBOUTLET

### ISSUE THREAD

**Issue by Manueldjz** [vitoziv/VIPhotoView#2]
*
This excellent for storyboard and imageView Object

///// .h

@property (weak, nonatomic) IBOutlet UIImageView *imageView;

/////// .m
self.imageView.hidden=YES;
    UIImage *image = self.imageView.image;
    VIPhotoView *photoView = [[VIPhotoView alloc] initWithFrame:self.view.bounds andImage:image];
    photoView.autoresizingMask = (1 << 6) -1;

```
[self.view addSubview:photoView];
```

**Comment by vitoziv** [comment]
Cool.I like storyboard show the result view. But it needs more codes, I think it's pretty useful in some simple case.

**Comment by Manueldjz** [comment]
yes, also included this lines.. for better appearance to hide status bar like application photo

////// .h

@interface YourController : UIViewController{
    BOOL shouldHideStatusBar;
}

///////  .m
-(void) showHideNavbar:(id) sender
{
    // write code to show/hide nav bar here
    // check if the Navigation Bar is shown
    if (self.navigationController.navigationBar.hidden == NO)
    {
        // hide the Navigation Bar
        [self.navigationController setNavigationBarHidden:YES animated:NO  ];

```
    //[[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleLightContent];
    [[UIApplication sharedApplication] setStatusBarHidden:YES withAnimation:UIStatusBarAnimationNone];

  CATransition* transition = [CATransition animation];
    transition.duration = 0.2;
    transition.timingFunction = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseInEaseOut];
    transition.type = kCATransitionFade; //kCATransitionMoveIn; //, kCATransitionPush, kCATransitionReveal, kCATransitionFade
    //transition.subtype = kCATransitionFromTop; //kCATransitionFromLeft, kCATransitionFromRight, kCATransitionFromTop, kCATransitionFromBottom

    [self.navigationController.view.layer addAnimation:transition forKey:nil];
    [[self navigationController] popViewControllerAnimated:NO];

}
// if Navigation Bar is already hidden
else if (self.navigationController.navigationBar.hidden == YES)
{
           // Show the Navigation Bar
    [self.navigationController setNavigationBarHidden:NO animated:NO];

    //[[UIApplication sharedApplication ] setStatusBarStyle: UIStatusBarStyleDefault];
    [[UIApplication sharedApplication] setStatusBarHidden:NO withAnimation:UIStatusBarAnimationNone];
```

 CATransition\* transition = [CATransition animation];
        transition.duration = 0.2;
        transition.timingFunction = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseInEaseOut];
        transition.type = kCATransitionFade; //kCATransitionMoveIn; //, kCATransitionPush, kCATransitionReveal, kCATransitionFade
        //transition.subtype = kCATransitionFromTop; //kCATransitionFromLeft, kCATransitionFromRight, kCATransitionFromTop, kCATransitionFromBottom
        [self.navigationController.view.layer addAnimation:transition forKey:nil];
        [[self navigationController] popViewControllerAnimated:NO];
    }
}

////////[super viewDidLoad]

UITapGestureRecognizer *tapGesture = [[UITapGestureRecognizer alloc]
                                          initWithTarget:self action:@selector(showHideNavbar:) ];
