### ISSUE TITLE
Frame issues

### ISSUE THREAD

**Issue by Amirnadi** [vitoziv/VIPhotoView#4]
Hi, 

I am using VIPhotoView in multiple applications. It was fine before, but now it is showing some issues with frames, When i first launch image via VIPhotoView, it shows scroll in view and image  as scrolldown. but when i double tap, it gets fixed in the  frame as suggested in view.

if anybody find a solution, update please

**Comment by vitoziv** [comment]
Could you show the demo code?

**Comment by Amirnadi** [comment]
just customise VIPhotoView code for my requirement
Please if you find any bug, solve this issue for me :)
[Archive.zip](https://github.com/vitoziv/VIPhotoView/files/779376/Archive.zip)

**Comment by Amirnadi** [comment]
I got this issue fixed. just added this line in viewDidLoad of my viewcontroller.

self.automaticallyAdjustsScrollViewInsets = false; :) Thanks 👍

**Comment by vitoziv** [comment]
cool
