### ISSUE TITLE
关于原图大小的问题

### ISSUE THREAD

**Issue by PengQiong** [vitoziv/VIPhotoView#5]
您好，我们显示图片在图片小于屏幕的大小的时候要求以原图大小居中显示，请问这样该如何实现？

**Comment by vitoziv** [comment]
VIPhotoView 没有支持这个哦。  原理是设置它的最小和最大缩放比例，需要判断图片大小是否小于视图显示区域。

**Comment by PengQiong** [comment]
我已经知道怎么处理这种情况了，将scrollview的minscale设置为自适应屏幕的图片缩放到小图的比例，然后将maxscale设置为这个比例的三倍，就可以了

**Comment by vitoziv** [comment]
很强，那这个 issue 就关闭了
